const schoolList = [
  "School of Computer Science and Engineering",
  "School of Law",
  "School of Liberal Arts and Sciences",
  "School of Economics and Public Policy",
  "School of Continuing Education",
  "School of Allied Healthcare",
  "School of Film Media and Creative Arts",
  "School of Design and Innovation",
  "School of Business",
];

export const demoCampusData = {
  schools: schoolList.map((name, index) => ({
    id: `demo-school-${index + 1}`,
    name,
    shortName: ["SCSE", "LAW", "SLAS", "SEPP", "SCE", "SAH", "SFMCA", "SDI", "SB"][index],
    description: [
      "Computing, AI, systems, and software engineering programs with active build communities.",
      "Legal studies, policy labs, moot teams, and public-interest research groups.",
      "Humanities, sciences, writing, psychology, and interdisciplinary inquiry.",
      "Economics, governance, public policy, civic data, and impact evaluation.",
      "Professional learning, upskilling, certifications, and evening cohorts.",
      "Healthcare, clinical systems, wellness, diagnostics, and public health projects.",
      "Film, media, communication, animation, performance, and creative production.",
      "Product design, interaction design, innovation, prototyping, and venture studios.",
      "Management, entrepreneurship, analytics, finance, and market strategy.",
    ][index],
    leadEmail: `school-${index + 1}@rvu.edu.in`,
    status: "active",
  })),
  clubs: [
    {
      id: "demo-club-ai-forge",
      slug: "demo-club-ai-forge",
      name: "AI Forge",
      category: "AI",
      school: "School of Computer Science and Engineering",
      tagline: "Building useful machine learning systems for campus-scale problems.",
      description: "AI Forge is a student lab for applied machine learning, prompt engineering, computer vision, and responsible AI. Members work in small squads, ship working prototypes, run paper-reading nights, and mentor beginners through hands-on notebooks instead of theory-only sessions.",
      doing: "Running a campus helpdesk bot sprint, a weekly model evaluation circle, and a mini-course on retrieval augmented generation.",
      highlights: ["Won internal AI buildathon", "Published campus FAQ bot prototype", "Hosted 6 paper jams"],
      founderName: "Aarav Menon",
      founderEmail: "aarav.menon@rvu.edu.in",
      facultyAdvisorName: "Dr. Kavya Rao",
      facultyAdvisorEmail: "kavya.rao@rvu.edu.in",
      currentPresidentName: "Nisha Iyer",
      currentPresidentEmail: "nisha.iyer@rvu.edu.in",
      join: "https://forms.gle/rvu-ai-forge",
      joinLink: "https://forms.gle/rvu-ai-forge",
      registrationOpen: true,
      status: "approved",
    },
    {
      id: "demo-club-codecraft",
      slug: "demo-club-codecraft",
      name: "CodeCraft",
      category: "Web Development",
      school: "School of Computer Science and Engineering",
      tagline: "Frontend, backend, APIs, and the craft of shipping polished software.",
      description: "CodeCraft helps RVU students move from tutorials to production habits. The club runs build nights, code reviews, Git workshops, deployment clinics, and collaborative product clones that teach accessibility, testing, and clean architecture.",
      doing: "Pairing first-year builders with seniors to ship a campus utilities toolkit.",
      highlights: ["40 student portfolios reviewed", "API bootcamp completed", "Deployed lost-and-found prototype"],
      founderName: "Vihaan Shah",
      founderEmail: "vihaan.shah@rvu.edu.in",
      facultyAdvisorName: "Prof. Meera Kulkarni",
      facultyAdvisorEmail: "meera.kulkarni@rvu.edu.in",
      currentPresidentName: "Rhea Suresh",
      currentPresidentEmail: "rhea.suresh@rvu.edu.in",
      join: "https://forms.gle/rvu-codecraft",
      joinLink: "https://forms.gle/rvu-codecraft",
      registrationOpen: true,
      status: "approved",
    },
    {
      id: "demo-club-design-studio",
      slug: "demo-club-design-studio",
      name: "RVU Design Studio",
      category: "Design",
      school: "School of Design and Innovation",
      tagline: "Research, prototype, test, and refine products that feel considered.",
      description: "RVU Design Studio brings together product designers, visual designers, researchers, and engineers. It focuses on user interviews, interface critique, design systems, service blueprints, and portfolio-ready case studies.",
      doing: "Redesigning student service journeys and building a shared component library for campus projects.",
      highlights: ["Ran usability lab day", "Created 18 portfolio case-study drafts", "Hosted design critique circle"],
      founderName: "Tara D'Souza",
      founderEmail: "tara.dsouza@rvu.edu.in",
      facultyAdvisorName: "Dr. Ishaan Bhat",
      facultyAdvisorEmail: "ishaan.bhat@rvu.edu.in",
      currentPresidentName: "Maya Krishnan",
      currentPresidentEmail: "maya.krishnan@rvu.edu.in",
      join: "https://forms.gle/rvu-design-studio",
      joinLink: "https://forms.gle/rvu-design-studio",
      registrationOpen: true,
      status: "approved",
    },
    {
      id: "demo-club-finance",
      slug: "demo-club-finance",
      name: "Capital Circle",
      category: "Finance",
      school: "School of Business",
      tagline: "Markets, investing, valuation, and financial literacy without the noise.",
      description: "Capital Circle studies markets through simulations, company teardown sessions, personal finance clinics, and valuation workshops. The club is beginner friendly, but its advanced track works on equity research briefs and portfolio strategy challenges.",
      doing: "Running a mock portfolio league and a valuation sprint on Indian consumer companies.",
      highlights: ["Hosted personal finance week", "Built model portfolio dashboard", "Published 12 company briefs"],
      founderName: "Kabir Nair",
      founderEmail: "kabir.nair@rvu.edu.in",
      facultyAdvisorName: "Prof. Shalini Gupta",
      facultyAdvisorEmail: "shalini.gupta@rvu.edu.in",
      currentPresidentName: "Ananya Rao",
      currentPresidentEmail: "ananya.rao@rvu.edu.in",
      join: "https://forms.gle/rvu-capital-circle",
      joinLink: "https://forms.gle/rvu-capital-circle",
      registrationOpen: false,
      status: "approved",
    },
    {
      id: "demo-club-moot",
      slug: "demo-club-moot",
      name: "Moot Court Society",
      category: "Law",
      school: "School of Law",
      tagline: "Argument, research, drafting, and courtroom discipline.",
      description: "The Moot Court Society prepares students for internal and external moots through memorial drafting clinics, argument practice, researcher training, and judge-led feedback rounds. It also hosts legal writing and citation workshops for new students.",
      doing: "Preparing teams for constitutional law and technology law moot competitions.",
      highlights: ["Inter-school moot finalists", "Citation clinic for first years", "Guest session with litigation counsel"],
      founderName: "Ira Thomas",
      founderEmail: "ira.thomas@rvu.edu.in",
      facultyAdvisorName: "Dr. Pranav Acharya",
      facultyAdvisorEmail: "pranav.acharya@rvu.edu.in",
      currentPresidentName: "Devika Sen",
      currentPresidentEmail: "devika.sen@rvu.edu.in",
      join: "https://forms.gle/rvu-moot",
      joinLink: "https://forms.gle/rvu-moot",
      registrationOpen: false,
      status: "approved",
    },
    {
      id: "demo-club-film",
      slug: "demo-club-film",
      name: "FrameWorks Film Club",
      category: "Film",
      school: "School of Film Media and Creative Arts",
      tagline: "Watch, write, shoot, edit, and screen stories.",
      description: "FrameWorks is RVU's film and visual storytelling community. It hosts screenings, scene breakdowns, cinematography drills, sound walks, short-film crews, and editing jams for students who want to understand cinema by making it.",
      doing: "Producing three 5-minute shorts and curating a monsoon screening series.",
      highlights: ["48-hour short film challenge", "Documentary walk through Jayanagar", "Campus open-air screening"],
      founderName: "Zoya Khan",
      founderEmail: "zoya.khan@rvu.edu.in",
      facultyAdvisorName: "Prof. Arjun Pillai",
      facultyAdvisorEmail: "arjun.pillai@rvu.edu.in",
      currentPresidentName: "Neil Fernandes",
      currentPresidentEmail: "neil.fernandes@rvu.edu.in",
      join: "https://forms.gle/rvu-frameworks",
      joinLink: "https://forms.gle/rvu-frameworks",
      registrationOpen: true,
      status: "approved",
    },
    {
      id: "demo-club-health",
      slug: "demo-club-health",
      name: "HealthTech Collective",
      category: "Healthcare",
      school: "School of Allied Healthcare",
      tagline: "Healthcare ideas shaped by empathy, evidence, and usable systems.",
      description: "HealthTech Collective connects healthcare students with designers, coders, and policy students to build practical tools for wellness, patient education, diagnostics workflows, and public health awareness.",
      doing: "Piloting a wellness check-in board and patient education micro-content templates.",
      highlights: ["Basic life support awareness camp", "Prototype clinic queue tracker", "Mental health resource map"],
      founderName: "Diya Mathew",
      founderEmail: "diya.mathew@rvu.edu.in",
      facultyAdvisorName: "Dr. Farah Siddiqui",
      facultyAdvisorEmail: "farah.siddiqui@rvu.edu.in",
      currentPresidentName: "Samar Jain",
      currentPresidentEmail: "samar.jain@rvu.edu.in",
      join: "https://forms.gle/rvu-healthtech",
      joinLink: "https://forms.gle/rvu-healthtech",
      registrationOpen: true,
      status: "approved",
    },
    {
      id: "demo-club-policy",
      slug: "demo-club-policy",
      name: "Policy Lab",
      category: "Policy",
      school: "School of Economics and Public Policy",
      tagline: "Data-backed civic thinking for students who want better systems.",
      description: "Policy Lab turns public problems into research briefs, explainers, field notes, and debate formats. Members learn survey design, policy memo writing, budget reading, and stakeholder analysis through real local questions.",
      doing: "Building a civic data explainer series on mobility, waste, and student housing.",
      highlights: ["Policy memo bootcamp", "Ward data walkthrough", "Public finance reading group"],
      founderName: "Reyansh Bedi",
      founderEmail: "reyansh.bedi@rvu.edu.in",
      facultyAdvisorName: "Prof. Nandita Menon",
      facultyAdvisorEmail: "nandita.menon@rvu.edu.in",
      currentPresidentName: "Aisha Kapoor",
      currentPresidentEmail: "aisha.kapoor@rvu.edu.in",
      join: "https://forms.gle/rvu-policy-lab",
      joinLink: "https://forms.gle/rvu-policy-lab",
      registrationOpen: true,
      status: "approved",
    },
    {
      id: "demo-club-marketing",
      slug: "demo-club-marketing",
      name: "Brand Sprint",
      category: "Marketing",
      school: "School of Business",
      tagline: "Campaigns, copy, consumer insight, and measurable creative work.",
      description: "Brand Sprint is a practical marketing club where students build launch plans, content calendars, campaign dashboards, and audience research reports. It collaborates with other clubs to promote real campus events.",
      doing: "Creating launch kits for club recruitment season and testing event poster variants.",
      highlights: ["Campus campaign teardown night", "Social media analytics clinic", "Brand voice workshop"],
      founderName: "Saanvi Reddy",
      founderEmail: "saanvi.reddy@rvu.edu.in",
      facultyAdvisorName: "Prof. Dev Mehta",
      facultyAdvisorEmail: "dev.mehta@rvu.edu.in",
      currentPresidentName: "Prisha Malhotra",
      currentPresidentEmail: "prisha.malhotra@rvu.edu.in",
      join: "https://forms.gle/rvu-brand-sprint",
      joinLink: "https://forms.gle/rvu-brand-sprint",
      registrationOpen: true,
      status: "approved",
    },
    {
      id: "demo-club-product",
      slug: "demo-club-product",
      name: "Product Guild",
      category: "Product",
      school: "School of Design and Innovation",
      tagline: "Problem discovery, roadmaps, metrics, and crisp product thinking.",
      description: "Product Guild trains students to think like product managers through discovery interviews, prioritization games, spec writing, analytics reviews, and cross-functional build simulations with designers and engineers.",
      doing: "Running a product teardown league and mentoring teams for the campus build expo.",
      highlights: ["PRD writing sprint", "Metrics maze workshop", "Product teardown tournament"],
      founderName: "Aditya Rao",
      founderEmail: "aditya.rao@rvu.edu.in",
      facultyAdvisorName: "Dr. Leela Nambiar",
      facultyAdvisorEmail: "leela.nambiar@rvu.edu.in",
      currentPresidentName: "Mehul Chawla",
      currentPresidentEmail: "mehul.chawla@rvu.edu.in",
      join: "https://forms.gle/rvu-product-guild",
      joinLink: "https://forms.gle/rvu-product-guild",
      registrationOpen: false,
      status: "approved",
    },
    {
      id: "demo-club-arts",
      slug: "demo-club-arts",
      name: "Ink and Stage",
      category: "Cultural",
      school: "School of Liberal Arts and Sciences",
      tagline: "Writing, spoken word, theatre, and campus performance.",
      description: "Ink and Stage is a creative home for poets, actors, playwrights, readers, and performers. The club mixes writing circles with rehearsals, open mics, script labs, and collaborative performances.",
      doing: "Preparing an evening of monologues, poems, and music for the arts courtyard.",
      highlights: ["Open mic with 28 performers", "Script lab for beginners", "Poetry zine issue one"],
      founderName: "Mira Bose",
      founderEmail: "mira.bose@rvu.edu.in",
      facultyAdvisorName: "Prof. Shruti Iyer",
      facultyAdvisorEmail: "shruti.iyer@rvu.edu.in",
      currentPresidentName: "Yash Agarwal",
      currentPresidentEmail: "yash.agarwal@rvu.edu.in",
      join: "https://forms.gle/rvu-ink-stage",
      joinLink: "https://forms.gle/rvu-ink-stage",
      registrationOpen: true,
      status: "approved",
    },
    {
      id: "demo-club-founders",
      slug: "demo-club-founders",
      name: "Founders Forum",
      category: "Business",
      school: "School of Business",
      tagline: "Student founders, operators, builders, and early venture experiments.",
      description: "Founders Forum supports students who want to test ideas seriously. It runs problem validation clinics, pitch practice, founder talks, customer interview drills, and demo days for early-stage student ventures.",
      doing: "Mentoring seven student venture ideas through problem validation and landing-page tests.",
      highlights: ["Demo day with 14 pitches", "Customer interview sprint", "Founder finance basics session"],
      founderName: "Armaan Gill",
      founderEmail: "armaan.gill@rvu.edu.in",
      facultyAdvisorName: "Prof. Raghav Sethi",
      facultyAdvisorEmail: "raghav.sethi@rvu.edu.in",
      currentPresidentName: "Kiara Joseph",
      currentPresidentEmail: "kiara.joseph@rvu.edu.in",
      join: "https://forms.gle/rvu-founders",
      joinLink: "https://forms.gle/rvu-founders",
      registrationOpen: true,
      status: "approved",
    },
  ],
  events: [
    {
      id: "demo-event-ai-agent-night",
      title: "AI Agent Build Night",
      description: "Teams build small campus assistants with retrieval, tool calls, and clear evaluation criteria.",
      date: "May 22",
      time: "5:30 PM",
      location: "Innovation Lab 2",
      host: "AI Forge",
      club: "AI Forge",
      type: "Club Event",
      tags: ["AI", "Product"],
      colors: ["#1f2937", "#b98935"],
      sort: 1,
      status: "published",
    },
    {
      id: "demo-event-code-review",
      title: "Code Review Clinic",
      description: "Bring a repo, get structured feedback on readability, architecture, accessibility, and tests.",
      date: "May 23",
      time: "4:00 PM",
      location: "Computer Lab A",
      host: "CodeCraft",
      club: "CodeCraft",
      type: "Club Event",
      tags: ["Web Development"],
      colors: ["#0f766e", "#f59e0b"],
      sort: 2,
      status: "published",
    },
    {
      id: "demo-event-design-crit",
      title: "Design Critique Studio",
      description: "A calm critique session for app screens, posters, portfolios, and product flows.",
      date: "May 24",
      time: "2:00 PM",
      location: "Design Studio 1",
      host: "RVU Design Studio",
      club: "RVU Design Studio",
      type: "Club Event",
      tags: ["Design", "Product"],
      colors: ["#7c3aed", "#eab308"],
      sort: 3,
      status: "published",
    },
    {
      id: "demo-event-law-tech",
      title: "Tech Law Moot Practice",
      description: "Practice oral rounds on privacy, platform liability, and digital evidence problems.",
      date: "May 25",
      time: "10:30 AM",
      location: "Moot Court Hall",
      host: "Moot Court Society",
      club: "Moot Court Society",
      type: "Club Event",
      tags: ["Law"],
      colors: ["#374151", "#c084fc"],
      sort: 4,
      status: "published",
    },
    {
      id: "demo-event-founder-office-hours",
      title: "Founder Office Hours",
      description: "Validate an idea, sharpen a pitch, or map the first customer experiment with mentors.",
      date: "May 26",
      time: "3:00 PM",
      location: "Business Studio",
      host: "Founders Forum",
      club: "Founders Forum",
      type: "Club Event",
      tags: ["Business", "Product", "Marketing"],
      colors: ["#92400e", "#14b8a6"],
      sort: 5,
      status: "published",
    },
    {
      id: "demo-event-public-health",
      title: "Public Health Map Sprint",
      description: "Create simple maps and explainers for student wellness resources around campus.",
      date: "May 27",
      time: "1:30 PM",
      location: "Allied Healthcare Lab",
      host: "HealthTech Collective",
      club: "HealthTech Collective",
      type: "Club Event",
      tags: ["Healthcare", "Design"],
      colors: ["#047857", "#f97316"],
      sort: 6,
      status: "published",
    },
    {
      id: "demo-event-film-screening",
      title: "Monsoon Screening: Short Films",
      description: "A curated student screening followed by a scene breakdown and crew matching session.",
      date: "May 28",
      time: "6:00 PM",
      location: "Open Air Theatre",
      host: "FrameWorks Film Club",
      club: "FrameWorks Film Club",
      type: "Club Event",
      tags: ["Film"],
      colors: ["#111827", "#dc2626"],
      sort: 7,
      status: "published",
    },
    {
      id: "demo-event-budget-reading",
      title: "How to Read a Public Budget",
      description: "A beginner session on finding line items, comparing allocations, and writing policy notes.",
      date: "May 29",
      time: "11:00 AM",
      location: "Seminar Hall B",
      host: "School of Economics and Public Policy",
      type: "School Event",
      tags: ["Finance", "Law"],
      colors: ["#155e75", "#eab308"],
      sort: 8,
      status: "published",
    },
    {
      id: "demo-event-brand-lab",
      title: "Poster A/B Testing Lab",
      description: "Test campus event creatives and learn how copy, hierarchy, and timing change signups.",
      date: "May 30",
      time: "4:30 PM",
      location: "Marketing Lab",
      host: "Brand Sprint",
      club: "Brand Sprint",
      type: "Club Event",
      tags: ["Marketing", "Design"],
      colors: ["#be123c", "#0ea5e9"],
      sort: 9,
      status: "published",
    },
    {
      id: "demo-event-research-methods",
      title: "Research Methods Bootcamp",
      description: "Learn surveys, interviews, consent, notes, and synthesis for student projects.",
      date: "Jun 01",
      time: "9:30 AM",
      location: "SLAS Seminar Room",
      host: "School of Liberal Arts and Sciences",
      type: "Faculty Event",
      tags: ["Design", "Policy"],
      colors: ["#4338ca", "#84cc16"],
      sort: 10,
      status: "published",
    },
    {
      id: "demo-event-portfolio-day",
      title: "Portfolio Review Day",
      description: "Design, code, film, law, and business students get quick portfolio feedback from faculty and peers.",
      date: "Jun 03",
      time: "2:00 PM",
      location: "Central Atrium",
      host: "RVU",
      type: "School Event",
      tags: ["Design", "Web Development", "Business"],
      colors: ["#0f172a", "#22c55e"],
      sort: 11,
      status: "published",
    },
    {
      id: "demo-event-product-teardown",
      title: "Product Teardown League",
      description: "Teams analyze onboarding, activation, retention, and monetization in popular apps.",
      date: "Jun 05",
      time: "5:00 PM",
      location: "Design Studio 2",
      host: "Product Guild",
      club: "Product Guild",
      type: "Club Event",
      tags: ["Product", "Business"],
      colors: ["#0369a1", "#f43f5e"],
      sort: 12,
      status: "published",
    },
    {
      id: "demo-event-open-mic",
      title: "Ink and Stage Open Mic",
      description: "Poetry, monologues, acoustic sets, and small performances from across RVU.",
      date: "Jun 06",
      time: "6:30 PM",
      location: "Arts Courtyard",
      host: "Ink and Stage",
      club: "Ink and Stage",
      type: "Club Event",
      tags: ["Film", "Design"],
      colors: ["#7f1d1d", "#facc15"],
      sort: 13,
      status: "published",
    },
    {
      id: "demo-event-equity-research",
      title: "Equity Research Jam",
      description: "Break down one company, build a simple model, and write a one-page investment note.",
      date: "Jun 08",
      time: "3:30 PM",
      location: "Finance Lab",
      host: "Capital Circle",
      club: "Capital Circle",
      type: "Club Event",
      tags: ["Finance", "Business"],
      colors: ["#064e3b", "#fbbf24"],
      sort: 14,
      status: "published",
    },
    {
      id: "demo-event-orientation",
      title: "Club Orientation Expo",
      description: "Meet active clubs, talk to core members, and find projects looking for contributors.",
      date: "Jun 10",
      time: "10:00 AM",
      location: "Main Quadrangle",
      host: "RVU Student Affairs",
      type: "School Event",
      tags: ["Business", "Design", "AI"],
      colors: ["#1f2937", "#d97706"],
      sort: 15,
      status: "published",
    },
    {
      id: "demo-event-past-hackday",
      title: "Campus Hack Day",
      description: "A one-day build sprint for utilities, dashboards, maps, and student services.",
      date: "Apr 18",
      time: "9:00 AM",
      location: "Innovation Lab",
      host: "CodeCraft",
      club: "CodeCraft",
      type: "Club Event",
      tags: ["Web Development", "AI"],
      colors: ["#334155", "#f97316"],
      sort: 90,
      past: true,
      status: "published",
    },
    {
      id: "demo-event-past-moot",
      title: "Internal Moot Finals",
      description: "Final rounds for the internal moot selection with faculty and alumni judges.",
      date: "Apr 21",
      time: "2:00 PM",
      location: "Moot Court Hall",
      host: "Moot Court Society",
      club: "Moot Court Society",
      type: "Club Event",
      tags: ["Law"],
      colors: ["#3f3f46", "#a855f7"],
      sort: 91,
      past: true,
      status: "published",
    },
    {
      id: "demo-event-past-demo-day",
      title: "Student Venture Demo Day",
      description: "Early venture teams shared prototypes, customer evidence, and next-step asks.",
      date: "Apr 25",
      time: "5:00 PM",
      location: "Auditorium",
      host: "Founders Forum",
      club: "Founders Forum",
      type: "Club Event",
      tags: ["Business", "Product"],
      colors: ["#78350f", "#10b981"],
      sort: 92,
      past: true,
      status: "published",
    },
  ],
  announcements: [
    {
      id: "demo-ann-ai-recruit",
      title: "AI Forge core team applications are open",
      description: "AI Forge is hiring research leads, build mentors, evaluation writers, and event coordinators for the next sprint cycle.",
      source: "AI Forge",
      type: "Club",
      tag: "Recruitment",
      time: "Today",
      status: "published",
      clubId: "demo-club-ai-forge",
    },
    {
      id: "demo-ann-expo",
      title: "Club Orientation Expo stall registrations",
      description: "Approved clubs can submit stall requirements, power needs, and volunteer rosters by May 24.",
      source: "RVU Student Affairs",
      sourceType: "school",
      type: "Faculty",
      tag: "Notice",
      time: "Today",
      status: "published",
    },
    {
      id: "demo-ann-design-portfolios",
      title: "Design portfolio review slots released",
      description: "Students can book 15-minute critique slots for app screens, service maps, case studies, and visual portfolios.",
      source: "RVU Design Studio",
      type: "Club",
      tag: "Update",
      time: "Yesterday",
      status: "published",
      clubId: "demo-club-design-studio",
    },
    {
      id: "demo-ann-law-moot",
      title: "Moot memorial submission window",
      description: "Teams shortlisted for practice rounds must upload draft memorials before 8 PM on May 23.",
      source: "Moot Court Society",
      type: "Club",
      tag: "Notice",
      time: "2 days ago",
      status: "published",
      clubId: "demo-club-moot",
    },
    {
      id: "demo-ann-health-volunteers",
      title: "Health awareness camp volunteer call",
      description: "HealthTech Collective needs volunteers for registration, crowd flow, wellness desk, and visual explainers.",
      source: "HealthTech Collective",
      type: "Club",
      tag: "Recruitment",
      time: "2 days ago",
      status: "published",
      clubId: "demo-club-health",
    },
    {
      id: "demo-ann-policy-brief",
      title: "Policy memo reading pack available",
      description: "The pre-read for the public budget workshop is available to all registered participants.",
      source: "School of Economics and Public Policy",
      sourceType: "school",
      type: "Faculty",
      tag: "Update",
      time: "3 days ago",
      status: "published",
    },
    {
      id: "demo-ann-brand-kit",
      title: "Recruitment poster templates published",
      description: "Brand Sprint has shared editable templates for clubs preparing recruitment announcements.",
      source: "Brand Sprint",
      type: "Club",
      tag: "Update",
      time: "3 days ago",
      status: "published",
      clubId: "demo-club-marketing",
    },
    {
      id: "demo-ann-film-crews",
      title: "Short film crew matching form",
      description: "FrameWorks is matching directors, editors, actors, sound recordists, and camera operators for three short films.",
      source: "FrameWorks Film Club",
      type: "Club",
      tag: "Recruitment",
      time: "4 days ago",
      status: "published",
      clubId: "demo-club-film",
    },
    {
      id: "demo-ann-product-league",
      title: "Product teardown league fixtures",
      description: "Round one teams and product categories have been published. Captains should confirm availability.",
      source: "Product Guild",
      type: "Club",
      tag: "Notice",
      time: "4 days ago",
      status: "published",
      clubId: "demo-club-product",
    },
    {
      id: "demo-ann-finance",
      title: "Mock portfolio leaderboard reset",
      description: "Capital Circle is resetting the mock portfolio league for the June cycle with new sector constraints.",
      source: "Capital Circle",
      type: "Club",
      tag: "Update",
      time: "5 days ago",
      status: "published",
      clubId: "demo-club-finance",
    },
    {
      id: "demo-ann-open-mic",
      title: "Open mic performer list closes soon",
      description: "Ink and Stage has 10 slots left for poetry, monologues, and acoustic performances.",
      source: "Ink and Stage",
      type: "Club",
      tag: "Recruitment",
      time: "5 days ago",
      status: "published",
      clubId: "demo-club-arts",
    },
    {
      id: "demo-ann-founder-mentors",
      title: "Founder mentor hour signups",
      description: "Founders Forum has opened founder mentor hour slots for idea validation and pitch feedback.",
      source: "Founders Forum",
      type: "Club",
      tag: "Update",
      time: "6 days ago",
      status: "published",
      clubId: "demo-club-founders",
    },
  ],
  projects: [
    {
      id: "demo-project-campus-helpdesk",
      title: "Campus Helpdesk RAG Bot",
      description: "Build a retrieval assistant that answers campus process questions from approved documents and flags uncertain answers.",
      tags: ["AI", "Web Development"],
      skills: ["JavaScript", "Embeddings", "Firebase", "UX writing"],
      expiry: "Jun 12",
      status: "open",
      score: 42,
      ownerId: "demo-user-nisha",
    },
    {
      id: "demo-project-event-heatmap",
      title: "Event Attendance Heatmap",
      description: "Analyze RSVP and check-in patterns to help clubs choose better rooms, days, and time slots.",
      tags: ["Product", "Finance", "Web Development"],
      skills: ["Data viz", "Firestore", "Analytics", "Product metrics"],
      expiry: "Jun 15",
      status: "open",
      score: 31,
      ownerId: "demo-user-mehul",
    },
    {
      id: "demo-project-wellness-map",
      title: "Student Wellness Resource Map",
      description: "Create a clear map of wellness resources, emergency contacts, quiet spaces, and support routes.",
      tags: ["Healthcare", "Design"],
      skills: ["Research", "Figma", "Content design", "Maps"],
      expiry: "Jun 18",
      status: "open",
      score: 27,
      ownerId: "demo-user-samar",
    },
    {
      id: "demo-project-legal-explainer",
      title: "Privacy Rights Explainer Series",
      description: "Write and design student-friendly explainers on privacy, consent, digital evidence, and platform terms.",
      tags: ["Law", "Design", "Marketing"],
      skills: ["Legal research", "Copywriting", "Illustration", "Editing"],
      expiry: "Jun 20",
      status: "open",
      score: 24,
      ownerId: "demo-user-devika",
    },
    {
      id: "demo-project-zine",
      title: "RVU Arts Zine Issue Two",
      description: "Collect writing, photography, film stills, and design spreads for the next campus arts zine.",
      tags: ["Film", "Design"],
      skills: ["Editorial design", "Writing", "Photography", "Layout"],
      expiry: "Jun 22",
      status: "open",
      score: 35,
      ownerId: "demo-user-yash",
    },
    {
      id: "demo-project-portfolio-crm",
      title: "Club Outreach CRM",
      description: "Prototype a lightweight tracker for sponsor outreach, speaker invites, partner follow-ups, and event leads.",
      tags: ["Business", "Marketing", "Web Development"],
      skills: ["Product specs", "React", "CRM flows", "Copy"],
      expiry: "Jun 25",
      status: "open",
      score: 19,
      ownerId: "demo-user-kiara",
    },
    {
      id: "demo-project-budget-dashboard",
      title: "Public Budget Dashboard",
      description: "Turn a small public budget dataset into an explorable dashboard with annotations and plain-language notes.",
      tags: ["Finance", "Law", "Web Development"],
      skills: ["Data cleaning", "Charts", "Policy writing", "Frontend"],
      expiry: "Jun 28",
      status: "open",
      score: 22,
      ownerId: "demo-user-aisha",
    },
    {
      id: "demo-project-short-film",
      title: "Five-Minute Short Film Crew",
      description: "Join a short film production team looking for sound, editing, production design, and assistant direction.",
      tags: ["Film", "Design"],
      skills: ["Editing", "Sound", "Production", "Storyboarding"],
      expiry: "Jun 09",
      status: "open",
      score: 29,
      ownerId: "demo-user-neil",
    },
    {
      id: "demo-project-registration-flow",
      title: "Club Registration Flow Redesign",
      description: "Research and redesign the experience of discovering clubs, applying, and tracking application status.",
      tags: ["Design", "Product"],
      skills: ["User interviews", "Wireframes", "Prototyping", "Usability tests"],
      expiry: "Jun 16",
      status: "open",
      score: 37,
      ownerId: "demo-user-maya",
    },
    {
      id: "demo-project-market-brief",
      title: "Campus Consumer Research Brief",
      description: "Run a small survey and produce a marketing insight brief about student food, commute, and study habits.",
      tags: ["Marketing", "Business"],
      skills: ["Survey design", "Analysis", "Slides", "Storytelling"],
      expiry: "Jun 19",
      status: "open",
      score: 18,
      ownerId: "demo-user-prisha",
    },
  ],
  hostRequests: [
    {
      id: "demo-request-cyber",
      name: "Advait Rao",
      email: "advait.rao@rvu.edu.in",
      type: "clubCore",
      clubId: "demo-club-codecraft",
      roleTitle: "Security Workshop Lead",
      description: "Wants to run secure coding sessions and CTF practice.",
      status: "pending",
    },
    {
      id: "demo-request-school",
      name: "Office of Design Outreach",
      email: "design.outreach@rvu.edu.in",
      type: "schoolRepresentative",
      schoolId: "School of Design and Innovation",
      roleTitle: "School Outreach Coordinator",
      description: "Needs access to post portfolio review and exhibition notices.",
      status: "pending",
    },
    {
      id: "demo-request-film",
      name: "Sara Mathew",
      email: "sara.mathew@rvu.edu.in",
      type: "clubCore",
      clubId: "demo-club-film",
      roleTitle: "Production Coordinator",
      description: "Will manage screening notices and crew calls.",
      status: "approved",
    },
  ],
  moderationFlags: [
    { id: "demo-flag-room", title: "Room changed but event not updated", collection: "events", targetId: "demo-event-product-teardown", status: "open", reason: "Outdated logistics" },
    { id: "demo-flag-link", title: "Registration link needs verification", collection: "clubs", targetId: "demo-club-product", status: "open", reason: "Closed form still visible" },
    { id: "demo-flag-project", title: "Project deadline unclear", collection: "projects", targetId: "demo-project-short-film", status: "reviewing", reason: "Expiry changed" },
  ],
  allUsers: [
    { id: "demo-user-nisha", name: "Nisha Iyer", email: "nisha.iyer@rvu.edu.in", role: "clubCore", school: "School of Computer Science and Engineering", interests: ["AI", "Product"] },
    { id: "demo-user-rhea", name: "Rhea Suresh", email: "rhea.suresh@rvu.edu.in", role: "clubCore", school: "School of Computer Science and Engineering", interests: ["Web Development"] },
    { id: "demo-user-maya", name: "Maya Krishnan", email: "maya.krishnan@rvu.edu.in", role: "clubCore", school: "School of Design and Innovation", interests: ["Design", "Product"] },
    { id: "demo-user-aisha", name: "Aisha Kapoor", email: "aisha.kapoor@rvu.edu.in", role: "clubCore", school: "School of Economics and Public Policy", interests: ["Law", "Finance"] },
    { id: "demo-user-samar", name: "Samar Jain", email: "samar.jain@rvu.edu.in", role: "clubCore", school: "School of Allied Healthcare", interests: ["Healthcare", "Design"] },
    { id: "demo-user-admin", name: "Super Admin Demo", email: "admin@rvu.edu.in", role: "superAdmin", school: "RVU" },
    { id: "demo-user-student1", name: "Anika Sharma", email: "anika.sharma@rvu.edu.in", role: "student", school: "School of Business", interests: ["Marketing", "Business"] },
    { id: "demo-user-student2", name: "Rohan Das", email: "rohan.das@rvu.edu.in", role: "student", school: "School of Law", interests: ["Law", "Policy"] },

  contentReviews: [
    { id: "demo-review-speaker", title: "External speaker poster copy", collection: "events", targetId: "demo-event-founder-office-hours", note: "Confirm speaker designation before publishing final poster.", status: "pending" },
    { id: "demo-review-health", title: "Health resource wording", collection: "projects", targetId: "demo-project-wellness-map", note: "Check support contact names and escalation language.", status: "pending" },
    { id: "demo-review-policy", title: "Budget explainer citations", collection: "projects", targetId: "demo-project-budget-dashboard", note: "Verify source links before promotion.", status: "approved" },
  ],
  siteSettings: [
    {
      id: "platform",
      eventCategories: ["Club Event", "Faculty Event", "School Event", "Workshop", "Competition", "Screening"],
      interestTags: ["AI", "Web Development", "Design", "Business", "Finance", "Marketing", "Product", "Film", "Law", "Healthcare", "Policy"],
      announcementTags: ["Recruitment", "Notice", "Update"],
      reviewRequired: false,
      bannedWords: ["spam", "fake"],
    },
  ],
  savedItems: [
    { id: "event_demo-event-ai-agent-night", itemId: "demo-event-ai-agent-night", type: "event", title: "AI Agent Build Night" },
    { id: "project_demo-project-registration-flow", itemId: "demo-project-registration-flow", type: "project", title: "Club Registration Flow Redesign" },
  ],
  followedClubs: [
    { id: "demo-club-ai-forge", clubId: "demo-club-ai-forge", clubName: "AI Forge" },
    { id: "demo-club-design-studio", clubId: "demo-club-design-studio", clubName: "RVU Design Studio" },
  ],
  rsvps: [
    { id: "demo-event-ai-agent-night", eventId: "demo-event-ai-agent-night", title: "AI Agent Build Night", status: "going" },
    { id: "demo-event-portfolio-day", eventId: "demo-event-portfolio-day", title: "Portfolio Review Day", status: "interested" },
  ],
  myApplications: [
    { id: "demo-project-campus-helpdesk", projectId: "demo-project-campus-helpdesk", title: "Campus Helpdesk RAG Bot", status: "pending" },
    { id: "demo-project-registration-flow", projectId: "demo-project-registration-flow", title: "Club Registration Flow Redesign", status: "accepted" },
  ],
};

function clone(value) {
  return JSON.parse(JSON.stringify(value));
}

function preferLive(liveItems, demoItems) {
  return liveItems && liveItems.length ? liveItems : clone(demoItems);
}

export function applyDemoCampusData(data = {}) {
  const demo = demoCampusData;
  const clubs = preferLive(data.clubs, demo.clubs);
  const events = preferLive(data.events, demo.events);
  const announcements = preferLive(data.announcements, demo.announcements);
  const projects = preferLive(data.projects, demo.projects);
  return {
    ...data,
    clubs,
    events,
    announcements,
    projects,
    hostRequests: preferLive(data.hostRequests, demo.hostRequests),
    moderationFlags: preferLive(data.moderationFlags, demo.moderationFlags),
    allUsers: preferLive(data.allUsers, demo.allUsers),
    allEvents: preferLive(data.allEvents, events),
    allAnnouncements: preferLive(data.allAnnouncements, announcements),
    allClubs: preferLive(data.allClubs, clubs),
    allSchools: preferLive(data.allSchools, demo.schools),
    contentReviews: preferLive(data.contentReviews, demo.contentReviews),
    savedItems: preferLive(data.savedItems, demo.savedItems),
    followedClubs: preferLive(data.followedClubs, demo.followedClubs),
    rsvps: preferLive(data.rsvps, demo.rsvps),
    myApplications: preferLive(data.myApplications, demo.myApplications),
    siteSettings: preferLive(data.siteSettings, demo.siteSettings),
  };
}
